name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./order/pom.xml
          mvn clean package -f ./menu/pom.xml
          mvn clean package -f ./notification/pom.xml
          mvn clean package -f ./orderlist/pom.xml
          mvn clean package -f ./coupon/pom.xml

      - name: Docker Build and push for Order
        uses: docker/build-push-action@v4
        with:
          context: ./order
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order:latest
            ghcr.io/${{ github.repository }}/order:${{ github.ref_name }}
            
      - name: Docker Build and push for Menu
        uses: docker/build-push-action@v4
        with:
          context: ./menu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/menu:latest
            ghcr.io/${{ github.repository }}/menu:${{ github.ref_name }}
            
      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
      - name: Docker Build and push for Orderlist
        uses: docker/build-push-action@v4
        with:
          context: ./orderlist
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/orderlist:latest
            ghcr.io/${{ github.repository }}/orderlist:${{ github.ref_name }}
            
      - name: Docker Build and push for Coupon
        uses: docker/build-push-action@v4
        with:
          context: ./coupon
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/coupon:latest
            ghcr.io/${{ github.repository }}/coupon:${{ github.ref_name }}
            
