apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderlist
  labels:
    app: orderlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderlist
  template:
    metadata:
      labels:
        app: orderlist
    spec:
      containers:
        - name: orderlist
          image: "username/orderlist:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
